### ISSUE TITLE
Trait with Associated Types

### ISSUE THREAD

**Issue by AmbitionXiang** [Lej77/cast_trait_object#2]
Hello, thank you for the excellent crate. It seems that It does not support Sub trait with associated type. That is, how to cast Super to Sub in the case below?

trait Super{}

trait Sub: Super {
    type Item;
}

It would be awesome if you could provide a solution!

Thanks,
AmbitionXiang

**Comment by Lej77** [comment]
Hi, glad it can be of use!

So note that this crate has quite limited support for generics and associated types. But currently it is possible to get some support with something like:

```rust
use cast_trait_object::*;

struct Test;

#[dyn_cast(Sub<Item = Test>)]
trait Super {}
#[dyn_cast(Sub<Item = Test>)]
impl Super for Test {}

trait Sub: Super {
    type Item;
}
impl Sub for Test {
    type Item = Test;
}
#[test]
fn it_works() {
    let a: &dyn Super = &Test;
    let _b: &dyn Sub<Item = Test> = a.dyn_cast::<dyn Sub<Item = Test>>().ok().unwrap();
}
```

It is possible that the situation could be improved somewhat but I'm not quite sure by how much. You could potentially try to implement the [`DynCast`](https://docs.rs/cast_trait_object/0.1.2/cast_trait_object/trait.DynCast.html) trait yourself for a type and get the convenient `dyn_cast` methods for free but it might not be worth the trouble.

**Comment by AmbitionXiang** [comment]
Hi~ Thanks for your tips and I have solved it. I’ll close the issue now.
